# Generated by Django 2.0 on 2017-12-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nataMaps', '0002_auto_20171204_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tract',
            name='countyName',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
