# Generated by Django 2.0 on 2017-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nataMaps', '0003_tract_countyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tract',
            name='geoid',
            field=models.CharField(max_length=11),
        ),
    ]
